= Bitácora de Juliana Sofia Novoa Solano

#table(
  columns: 4,
  table.header([*n°*], [*Descripción*], [*Fecha*], [*Actividad realizada*]),
  [1],
  [Se realizó el diagrama de contenedores (usando C4 model) en base a los casos de uso definidos y el diagrama de contexto anteriormente realizado.],
  [2026-08-23],
  [Diagrama de Contenedores],
  [2],
  [Se realizó el diagrama de componentes (usando el C4 model) para la aplicación móvil.],
  [2026-09-07],
  [Diagrama de Componentes - Aplicación móvil],
  [3],
  [Se subió una nuerva versión del diagrama de componentes del sistema móvil con cambios y mejoras.],
  [2026-09-12],
  [Diagrama de Componentes (Mejora) - Aplicación móvil],
  [4],
  [Se realizó la primera iteración del diagrama de código para móvil de pagos.],
  [2026-09-14],
  [Diagrama de Código para pagos - Aplicación móvil],
  [5],
  [Se realizó el diagrama para el componente financiero móvil.],
  [2026-09-14],
  [Diagrama de Código financiero - Aplicación móvil],
  [6],
  [Se realizó el grafo de navegación de la web.],
  [2026-09-15],
  [Grafo de navegación - Aplicación web],
  [7],
  [Realice la implementación (individualmente) de los casos de uso  06, 07 y 08 en el ms-cuenta, junto a Sara Rodriguez realice el 21 y 22.],
  [2026-09-19],
  [Implementación de Casos de uso (6 - 8) (21 -22 )],
  [8],
  [Realice la implementación del casu de uso 10 (certificados bancarios).],
  [2026-09-19],
  [Implementación de Casos de uso #10 - Certificados Bancarios],
)
